### ISSUE TITLE
tasks.Init file is missing

### ISSUE THREAD

**Issue by stonecauldron** [jeffsvajlenko/BigCloneEval#10]
The last step of the installation section in the README asks the user to run the `init` script inside the `commands` directory.

Running the script, however, results in a failure:
```
Error: Could not find or load main class tasks.Init
```

This comes from the fact that there is no `tasks.Init` file in the top level directory of the project. Was running this script only necessary in prior versions of BigCloneEval?

**Comment by jeffsvajlenko** [comment]
You will need to run 'make' in the root directory to build the source code.  I've updated the ReadMe since this was missing.  It should work after this.
