### ISSUE TITLE
evaluate tool error

### ISSUE THREAD

**Issue by qw3ry** [jeffsvajlenko/BigCloneEval#11]
There is a bug in the `./evaluateTool` command:
```
> ./evaluateTool -t1 -mis0 -mil0 -mip0 -mit0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at tasks.EvaluateTool.main(EvaluateTool.java:243)
```

This is caused by the CLI parser, thinking `-m` was a matcher. It tries to split the matcher string and fails.

Suggested solution:
- Put a error message when the matcher string cannot be parsed
- use two long option names for those min/max options instead of a short and a long option, so the call above would become `./evaluateTool -t1 --mis0 --mil0 --mip0 --mit0`

I'd be happy to do a PR for this, if this is wanted.

While browsing the code, I was thinking of [picocli](https://picocli.info/quick-guide.html) which would make the whole option parsing more compact. If this is an option, I could port the whole project from apache cli to picocli as part of the PR, if you are interested.

**Comment by jeffsvajlenko** [comment]
Feel free :).
