### ISSUE TITLE
Process to typify the clones of the big clone bench

### ISSUE THREAD

**Issue by nikitamehrotra12** [jeffsvajlenko/BigCloneEval#13]
Hi,

Could you please provide details of the typifying process that you have used to assign the categories to the clone pairs. It was automated or have been done manually?

Many thanks for your help.

**Comment by qw3ry** [comment]
According to [this paper](https://ieeexplore.ieee.org/document/6976121) the clones were found manually

**Comment by nikitamehrotra12** [comment]
No, I was not asking for the tagging part. After tagging they have typified the clones with its type, so I wanted to know whether it was automated or manual.
