### ISSUE TITLE
Cannot open the link you give

### ISSUE THREAD

**Issue by FlyGreyWolf** [jeffsvajlenko/BigCloneEval#16]

**Comment by FlyGreyWolf** [comment]
Cannot open the link you give

**Comment by milocyning** [comment]
me too.

**Comment by jeffsvajlenko** [comment]
It appears the BigCloneEval downloads link is not available on some ISPs in China.  I have updated the GitHub readme to include the direct download links (dropbox).  Do let me know if you still experience problems.  Also, let me know if there is a web host and download host that is reliable in China.  I am currently using weebly (webhost) and dropbox (file host).

**Comment by milocyning** [comment]
@jeffsvajlenko ok, it's fine.

**Comment by milocyning** [comment]
Mirrors:
Database, BigCloneEval Version: 
```
https://www.dropbox.com/s/z2k8r78l63r68os/BigCloneBench_BCEvalVersion.tar.gz?dl=0
```
IJaDataset, BigCloneEval Version: 
```
https://www.dropbox.com/s/xdio16u396imz29/IJaDataset_BCEvalVersion.tar.gz?dl=0
```

**Comment by FlyGreyWolf** [comment]
Thank you very much!!!
