### ISSUE TITLE
importClones command problem

### ISSUE THREAD

**Issue by sudhirbelagali** [jeffsvajlenko/BigCloneEval#19]
I am getting this error, I was able to detect clones using Nicad6.0, It works great, but when I execute ./importClones -t 1  -c ../nicad.clones I got this error, I tried many times. Please help me Thank you in advance

(base) mrbot@bot:~/Desktop/bigcloneeval/BigCloneEval/commands$ ./importClones -t 1  -c ../nicad.clones 
	Some error occured with the database connection or interaction.

	Please try a fresh copy of the datbase, and report the error to.

	the developers.
org.h2.jdbc.JdbcSQLException: NULL not allowed for column "NAME1"; SQL statement:
INSERT INTO tool_1_clones SELECT * FROM csvread('/home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/commands/../nicad.clones','type1,name1,startline1,endline1,type2,name2,startline2,endline2') [23502-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:308)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:726)
	at org.h2.command.dml.Insert.addRow(Insert.java:196)
	at org.h2.command.dml.Insert.insertRows(Insert.java:173)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:132)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:117)
	at com.jolbox.bonecp.StatementHandle.executeUpdate(StatementHandle.java:497)
	at database.Clones.importClones(Clones.java:40)
	at tasks.ImportClones.main(ImportClones.java:121)

**Comment by jeffsvajlenko** [comment]
Hi @sudhirbelagali, could you include a snippet of your 'nicad.clones' file?  I can give it a try.

Each line in the file should have a format:

type1,name1,startline1,endline1,type2,name2,endline2,type2

Where 'type' is the root folder of IJaDataset (one of default, selected or samples), name is the name of the file, and start/endline of the code fragments.

For example:
default,10000.java,10,20,selected,12353.java,20,30

**Comment by sudhirbelagali** [comment]
Thank You for the reply sir,
Here is the content of my nicad.clones

NiCad Clone Detector v6.0 (1.6.20)
config=/usr/local/lib/nicad6/config/myconfig.cfg
system=/home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5_functions-blind-clones
threshold=0.30
granularity=functions
language=java
transform=none
rename=blind
filter=none
abstract=literal
normalize=none
cluster=no
report=yes
include=
exclude=
Tue Jul 14 10:09:54 IST 2020
Extracting functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5_functions-blind-clones
Extracted 0 functions
Applying blind renaming to extracted functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5_functions-blind-clones
*** ERROR: Renaming failed, code 99
Detailed log in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5_functions-blind-clones_functions-clones-2020-07-14-10:09:54.log
NiCad Clone Detector v6.0 (1.6.20)
config=/usr/local/lib/nicad6/config/myconfig.cfg
system=/home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5
threshold=0.30
granularity=functions
language=java
transform=none
rename=blind
filter=none
abstract=literal
normalize=none
cluster=no
report=yes
include=
exclude=
Tue Jul 14 10:09:54 IST 2020
Extracting functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5
Extracted 200 functions
Applying blind renaming to extracted functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5
Applying abstraction of literal to extracted functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5
Finding clones between 10 and 10000 lines at UPI threshold 0.30
Found 46 clone pairs
Getting original sources for clones
Making HTML reports
Done.
Detailed log in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5_functions-clones-2020-07-14-10:09:54.log
Results in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5_functions-blind-abstract-clones/
Report in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/5_functions-blind-abstract-clones/*_functions*-clones-0.30-*.html
Tue Jul 14 10:09:55 IST 2020
sample,FileChooser.java,67,94,sample,FileChooser.java,96,123
sample,FileChooser.java,38,65,sample,FileChooser.java,96,123
sample,FileChooser.java,9,36,sample,FileChooser.java,96,123
sample,FileChooser.java,38,65,sample,FileChooser.java,67,94
sample,FileChooser.java,9,36,sample,FileChooser.java,67,94
sample,FileChooser.java,9,36,sample,FileChooser.java,38,65
sample,BubbleSort.java,57,73,sample,BubbleSort.java,93,109
sample,BubbleSort.java,57,73,sample,BubbleSort.java,129,145
sample,BubbleSort.java,57,73,sample,BubbleSort.java,165,181
sample,BubbleSort.java,57,73,sample,BubbleSort.java,201,217
sample,BubbleSort.java,57,73,sample,BubbleSort.java,238,254
sample,BubbleSort.java,21,37,sample,BubbleSort.java,57,73
sample,BubbleSort.java,93,109,sample,BubbleSort.java,129,145
sample,BubbleSort.java,93,109,sample,BubbleSort.java,165,181
sample,BubbleSort.java,93,109,sample,BubbleSort.java,201,217
sample,BubbleSort.java,93,109,sample,BubbleSort.java,238,254
sample,BubbleSort.java,21,37,sample,BubbleSort.java,93,109
sample,BubbleSort.java,129,145,sample,BubbleSort.java,165,181
sample,BubbleSort.java,129,145,sample,BubbleSort.java,201,217
sample,BubbleSort.java,129,145,sample,BubbleSort.java,238,254
sample,BubbleSort.java,21,37,sample,BubbleSort.java,129,145
sample,BubbleSort.java,165,181,sample,BubbleSort.java,201,217
sample,BubbleSort.java,165,181,sample,BubbleSort.java,238,254
sample,BubbleSort.java,21,37,sample,BubbleSort.java,165,181
sample,BubbleSort.java,201,217,sample,BubbleSort.java,238,254
sample,BubbleSort.java,21,37,sample,BubbleSort.java,201,217
sample,BubbleSort.java,21,37,sample,BubbleSort.java,238,254
selected,1729199.java,33,49,selected,1729199.java,57,69
sample,BubbleSort.java,147,163,sample,BubbleSort.java,183,199
sample,BubbleSort.java,3,19,sample,BubbleSort.java,183,199
sample,BubbleSort.java,111,127,sample,BubbleSort.java,183,199
sample,BubbleSort.java,39,55,sample,BubbleSort.java,183,199
sample,BubbleSort.java,75,91,sample,BubbleSort.java,183,199
sample,BubbleSort.java,3,19,sample,BubbleSort.java,147,163
sample,BubbleSort.java,111,127,sample,BubbleSort.java,147,163
sample,BubbleSort.java,39,55,sample,BubbleSort.java,147,163
sample,BubbleSort.java,75,91,sample,BubbleSort.java,147,163
sample,BubbleSort.java,3,19,sample,BubbleSort.java,111,127
sample,BubbleSort.java,3,19,sample,BubbleSort.java,39,55
sample,BubbleSort.java,3,19,sample,BubbleSort.java,75,91
sample,BubbleSort.java,39,55,sample,BubbleSort.java,111,127
sample,BubbleSort.java,75,91,sample,BubbleSort.java,111,127
sample,BubbleSort.java,39,55,sample,BubbleSort.java,75,91
sample,DownloadWebpage.java,20,30,sample,DownloadWebpage.java,55,67
sample,ShuffleArrayInPlace.java,16,32,sample,ShuffleArrayInPlace.java,50,66
sample,PrimeFactors.java,6,16,sample,PrimeFactors.java,18,28
NiCad Clone Detector v6.0 (1.6.20)
config=/usr/local/lib/nicad6/config/myconfig.cfg
system=/home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2_functions-blind-clones
threshold=0.30
granularity=functions
language=java
transform=none
rename=blind
filter=none
abstract=literal
normalize=none
cluster=no
report=yes
include=
exclude=
Tue Jul 14 10:09:55 IST 2020
Extracting functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2_functions-blind-clones
Extracted 0 functions
Applying blind renaming to extracted functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2_functions-blind-clones
*** ERROR: Renaming failed, code 99
Detailed log in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2_functions-blind-clones_functions-clones-2020-07-14-10:09:55.log
NiCad Clone Detector v6.0 (1.6.20)
config=/usr/local/lib/nicad6/config/myconfig.cfg
system=/home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2
threshold=0.30
granularity=functions
language=java
transform=none
rename=blind
filter=none
abstract=literal
normalize=none
cluster=no
report=yes
include=
exclude=
Tue Jul 14 10:09:55 IST 2020
Extracting functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2
*** Warning: 3 source files failed to parse
Extracted 5682 functions
Applying blind renaming to extracted functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2
Applying abstraction of literal to extracted functions from java files in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2
Finding clones between 10 and 10000 lines at UPI threshold 0.30
Found 707 clone pairs
Getting original sources for clones
Making HTML reports
Done.
Detailed log in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2_functions-clones-2020-07-14-10:09:55.log
Results in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2_functions-blind-abstract-clones/
Report in /home/mrrobot/Desktop/SanjaySir/bigcloneeval/BigCloneEval/ijadataset/bcb_reduced/2_functions-blind-abstract-clones/*_functions*-clones-0.30-*.html
Tue Jul 14 10:10:06 IST 2020
selected,2484880.java,24,219,selected,1913721.java,24,183
selected,325038.java,228,426,selected,2447244.java,206,376
selected,437563.java,28,176,selected,309267.java,28,176
selected,437563.java,28,176,selected,390608.java,28,176
selected,437563.java,28,176,selected,507924.java,31,179
selected,437563.java,28,176,selected,1187016.java,26,174
selected,390608.java,28,176,selected,309267.java,28,176
selected,507924.java,31,179,selected,309267.java,28,176
selected,1187016.java,26,174,selected,309267.java,28,176
selected,507924.java,31,179,selected,390608.java,28,176
selected,1187016.java,26,174,selected,390608.java,28,176
selected,507924.java,31,179,selected,1187016.java,26,174
selected,2189277.java,174,298,selected,774986.java,173,297
selected,1282827.java,587,692,selected,2106140.java,798,903
selected,2189277.java,421,532,selected,774986.java,416,526
selected,92248.java,485,585,selected,1076248.java,394,494
selected,1994264.java,278,383,selected,688744.java,278,383
selected,1282827.java,739,840,selected,2106140.java,951,1052
selected,1282827.java,1103,1190,selected,1033020.java,781,848
selected,1282827.java,1103,1190,selected,2106140.java,1311,1378
selected,1080456.java,229,309,selected,2537513.java,231,308
selected,2106140.java,1311,1378,selected,1033020.java,781,848
selected,977931.java,83,157,selected,1071038.java,150,224
selected,1282827.java,963,1029,selected,2106140.java,1175,1241
selected,1282827.java,963,1029,selected,1033020.java,657,711

**Comment by sudhirbelagali** [comment]
> Hi @sudhirbelagali, could you include a snippet of your 'nicad.clones' file? I can give it a try.
> 
> Each line in the file should have a format:
> 
> type1,name1,startline1,endline1,type2,name2,endline2,type2
> 
> Where 'type' is the root folder of IJaDataset (one of default, selected or samples), name is the name of the file, and start/endline of the code fragments.
> 
> For example:
> default,1
0000.java,10,20,selected,12353.java,20,30
