### ISSUE TITLE
Is there a partitionInput command?

### ISSUE THREAD

**Issue by huashijiacuo** [jeffsvajlenko/BigCloneEval#3]
Dear Sir:
   ### I am trying to use the BigCloneEval, and I found that there is not a partitionInput file.I used the command "./detectClones -tr ~/nicadRunner -o ~/clones -mf 2000". 

### The myconfig is defaultreport in NiCad4.0/config. The nicadRunner:
*************************************
#!/bin/bash
ulimit -s hard
root=`dirname $1`
dir=`basename $1`
path=$root/$dir
cd /home/shi/software/NiCad-4.0/
./nicad4 functions java "$path" defaultreport > /dev/null 2> /dev/null
java -jar Convert.jar ${path}_functions-blind-abstract-clones/${dir}_functions-blind-abstract-clones-0.30.xml 2> /dev/null

### The output clones is a blank file and some xml file in the ijadataset/bcb_reduced/.  I read the README. I thinke the output clones should be the format csv file and there should be some result.

**Comment by clonebench** [comment]
Sorry, the initial tool runner for NiCad was just an example and there was no Convert.jar.  I provide a new tool runner that should work on more systems that uses built in Linux commands to parse and convert the clone report format.  However, you may need to test and modify the tool runner for your system.

**Comment by jeffsvajlenko** [comment]
RE: partition, looks like I missed a bash and command prompt script for this, added now to master.
