### ISSUE TITLE
meaning of the 'selected', 'default' and 'sample' folders.

### ISSUE THREAD

**Issue by helenawang** [jeffsvajlenko/BigCloneEval#5]
Would you like to explain the meaning of the 'selected', 'default' and 'sample' folders? Were these names given by BigCloneBench or IJaDataset?

**Comment by jeffsvajlenko** [comment]
Selected and Default were given by IJaDataset creators.  They indicate 'Selected' were Java classes with a named package, while Default were ones in the default package.  This has no special meaning for BigCloneBench.

The classes in the sample/ folder are ones we added to the data-set during benchmark creation.  This is explained further in the publication.
