### ISSUE TITLE
VM import error with virtualbox

### ISSUE THREAD

**Issue by qw3ry** [jeffsvajlenko/BigCloneEval#9]
Virtualbox reports an SHA1 mismatch on import:

Digest mismatch (VERR_NOT_EQUAL): Attribute 'SHA1' on 'BigCloneEval-disk1.vmdk' does not match ('a05158d159d8bde33b0ef5a7d8aa8118b777879f' vs. 'eb8c1b8fd8167c800f59018ddef45622921d1c36').

**Comment by jeffsvajlenko** [comment]
The VM version is a bit dated now, I do recommend using the updated version in the GitHub repository.
